USE [master]
GO
/****** Object:  Database [inv_qr]    Script Date: 28/01/2026 11:49:14 a. m. ******/
CREATE DATABASE [inv_qr]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'inv_qr', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\inv_qr.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'inv_qr_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\inv_qr_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [inv_qr] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [inv_qr].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [inv_qr] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [inv_qr] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [inv_qr] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [inv_qr] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [inv_qr] SET ARITHABORT OFF 
GO
ALTER DATABASE [inv_qr] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [inv_qr] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [inv_qr] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [inv_qr] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [inv_qr] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [inv_qr] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [inv_qr] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [inv_qr] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [inv_qr] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [inv_qr] SET  DISABLE_BROKER 
GO
ALTER DATABASE [inv_qr] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [inv_qr] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [inv_qr] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [inv_qr] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [inv_qr] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [inv_qr] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [inv_qr] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [inv_qr] SET RECOVERY FULL 
GO
ALTER DATABASE [inv_qr] SET  MULTI_USER 
GO
ALTER DATABASE [inv_qr] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [inv_qr] SET DB_CHAINING OFF 
GO
ALTER DATABASE [inv_qr] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [inv_qr] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [inv_qr] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [inv_qr] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [inv_qr] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [inv_qr] SET QUERY_STORE = ON
GO
ALTER DATABASE [inv_qr] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [inv_qr]
GO
/****** Object:  Table [dbo].[tab_activotec]    Script Date: 28/01/2026 11:49:15 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tab_activotec](
	[id_activo] [int] IDENTITY(1,1) NOT NULL,
	[serial] [varchar](100) NULL,
	[codigo_qr] [varchar](50) NULL,
	[hostname] [varchar](100) NULL,
	[referencia] [varchar](100) NULL,
	[mac_activo] [varchar](17) NULL,
	[ip_equipo] [varchar](15) NULL,
	[id_tipoequi] [int] NOT NULL,
	[id_marca] [int] NOT NULL,
	[id_modelo] [int] NULL,
	[estado] [varchar](20) NOT NULL,
	[cod_nom_responsable] [varchar](6) NULL,
	[id_padre_activo] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id_activo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[serial] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[codigo_qr] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tab_actualizaciones]    Script Date: 28/01/2026 11:49:15 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tab_actualizaciones](
	[id_evento] [int] IDENTITY(1,1) NOT NULL,
	[fecha] [datetime] NULL,
	[id_activo] [int] NOT NULL,
	[tipo_evento] [varchar](50) NOT NULL,
	[desc_evento] [text] NOT NULL,
	[usuario_sistema] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_evento] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tab_area]    Script Date: 28/01/2026 11:49:15 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tab_area](
	[id_area] [int] IDENTITY(1,1) NOT NULL,
	[nom_area] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_area] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[nom_area] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tab_empleados]    Script Date: 28/01/2026 11:49:15 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tab_empleados](
	[cod_nom] [varchar](6) NOT NULL,
	[nom_emple] [varchar](100) NOT NULL,
	[id_area] [int] NOT NULL,
	[activo] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[cod_nom] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tab_marca]    Script Date: 28/01/2026 11:49:15 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tab_marca](
	[id_marca] [int] IDENTITY(1,1) NOT NULL,
	[nom_marca] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_marca] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[nom_marca] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tab_modelo]    Script Date: 28/01/2026 11:49:15 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tab_modelo](
	[id_modelo] [int] IDENTITY(1,1) NOT NULL,
	[nom_modelo] [varchar](100) NOT NULL,
	[id_marca] [int] NOT NULL,
	[id_tipoequi] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id_modelo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tab_tipos]    Script Date: 28/01/2026 11:49:15 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tab_tipos](
	[id_tipoequi] [int] IDENTITY(1,1) NOT NULL,
	[nom_tipo] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_tipoequi] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[nom_tipo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tab_usuarios]    Script Date: 28/01/2026 11:49:15 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tab_usuarios](
	[id_usuario] [int] IDENTITY(1,1) NOT NULL,
	[username] [varchar](50) NOT NULL,
	[contraseña] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Hostname_Unique_NotNull]    Script Date: 28/01/2026 11:49:15 a. m. ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Hostname_Unique_NotNull] ON [dbo].[tab_activotec]
(
	[hostname] ASC
)
WHERE ([hostname] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tab_actualizaciones] ADD  DEFAULT (getdate()) FOR [fecha]
GO
ALTER TABLE [dbo].[tab_empleados] ADD  DEFAULT ((1)) FOR [activo]
GO
ALTER TABLE [dbo].[tab_activotec]  WITH CHECK ADD  CONSTRAINT [FK_Activo_Empleado] FOREIGN KEY([cod_nom_responsable])
REFERENCES [dbo].[tab_empleados] ([cod_nom])
GO
ALTER TABLE [dbo].[tab_activotec] CHECK CONSTRAINT [FK_Activo_Empleado]
GO
ALTER TABLE [dbo].[tab_activotec]  WITH CHECK ADD  CONSTRAINT [FK_Activo_Marca] FOREIGN KEY([id_marca])
REFERENCES [dbo].[tab_marca] ([id_marca])
GO
ALTER TABLE [dbo].[tab_activotec] CHECK CONSTRAINT [FK_Activo_Marca]
GO
ALTER TABLE [dbo].[tab_activotec]  WITH CHECK ADD  CONSTRAINT [FK_Activo_Modelo] FOREIGN KEY([id_modelo])
REFERENCES [dbo].[tab_modelo] ([id_modelo])
GO
ALTER TABLE [dbo].[tab_activotec] CHECK CONSTRAINT [FK_Activo_Modelo]
GO
ALTER TABLE [dbo].[tab_activotec]  WITH CHECK ADD  CONSTRAINT [FK_Activo_Padre] FOREIGN KEY([id_padre_activo])
REFERENCES [dbo].[tab_activotec] ([id_activo])
GO
ALTER TABLE [dbo].[tab_activotec] CHECK CONSTRAINT [FK_Activo_Padre]
GO
ALTER TABLE [dbo].[tab_activotec]  WITH CHECK ADD  CONSTRAINT [FK_Activo_Tipo] FOREIGN KEY([id_tipoequi])
REFERENCES [dbo].[tab_tipos] ([id_tipoequi])
GO
ALTER TABLE [dbo].[tab_activotec] CHECK CONSTRAINT [FK_Activo_Tipo]
GO
ALTER TABLE [dbo].[tab_actualizaciones]  WITH CHECK ADD  CONSTRAINT [FK_Historial_Activo] FOREIGN KEY([id_activo])
REFERENCES [dbo].[tab_activotec] ([id_activo])
GO
ALTER TABLE [dbo].[tab_actualizaciones] CHECK CONSTRAINT [FK_Historial_Activo]
GO
ALTER TABLE [dbo].[tab_empleados]  WITH CHECK ADD  CONSTRAINT [FK_Empleado_Area] FOREIGN KEY([id_area])
REFERENCES [dbo].[tab_area] ([id_area])
GO
ALTER TABLE [dbo].[tab_empleados] CHECK CONSTRAINT [FK_Empleado_Area]
GO
ALTER TABLE [dbo].[tab_modelo]  WITH CHECK ADD  CONSTRAINT [FK_Modelo_Marca] FOREIGN KEY([id_marca])
REFERENCES [dbo].[tab_marca] ([id_marca])
GO
ALTER TABLE [dbo].[tab_modelo] CHECK CONSTRAINT [FK_Modelo_Marca]
GO
ALTER TABLE [dbo].[tab_modelo]  WITH CHECK ADD  CONSTRAINT [FK_Modelo_Tipo] FOREIGN KEY([id_tipoequi])
REFERENCES [dbo].[tab_tipos] ([id_tipoequi])
GO
ALTER TABLE [dbo].[tab_modelo] CHECK CONSTRAINT [FK_Modelo_Tipo]
GO
ALTER TABLE [dbo].[tab_activotec]  WITH CHECK ADD CHECK  (([estado]='Baja' OR [estado]='En Reparación' OR [estado]='Malo' OR [estado]='Bueno'))
GO
USE [master]
GO
ALTER DATABASE [inv_qr] SET  READ_WRITE 
GO
